version: "3.9"
services:
  priory-game:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: priory-game
    tty: true
    stdin_open: true
    environment:
      - PRIORY_SAVE_SECRET=SET_A_LONG_RANDOM_SECRET
    volumes:
      - ./saves:/app/saves
